services:
  - name: react-app
    buildCommand: cd client/src && npm install
    startCommand: cd client/src && npm start
    env:
      - name: PORT
        value: 3000

  - name: node-app
    buildCommand: cd client/src/api && npm install
    startCommand: cd client/src/api && node index.js
    env:
      - name: PORT
        value: 8080

  - name: json-server
    buildCommand: cd client/src/api && npm install
    startCommand: cd client/src/api && npx json-server --watch db.json --port 3001
    env:
      - name: PORT
        value: 3001
