const TYPES = {
	ADD_PRODUCT_TO_CART: "ADD_PRODUCT_TO_CART",
	DELETE_ALL_FROM_CART: "DELETE_ALL_FROM_CART",
	DELETE_PRODUCT_FROM_CART: "DELETE_PRODUCT_FROM_CART",
	CALCULATE_TOTAL_PRICE_OF_THE_CART: "CALCULATE_TOTAL_PRICE_OF_THE_CART",
	ADD_NEW_ITEM_TO_CART: "ADD_NEW_ITEM_TO_CART",
};

export default TYPES;
